language: minimal
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin
  - VERSION=$(git rev-list --count HEAD)
script:
  - docker build -t "$DOCKER_REGISTRY"/"$DOCKER_IMAGE_NAME":"$VERSION" .
deploy:
  - provider: script
    script: docker push "$DOCKER_REGISTRY"/"$DOCKER_IMAGE_NAME":"$VERSION"
    on:
      tags: true